name: React App Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::129950599618:role/oidc-role
          aws-region: us-east-1

      - name: Test AWS Connection
        run: aws sts get-caller-identity

      - name: Deploy React App to EC2
        run: |
          aws ssm send-command \
            --instance-ids i-06f806dae5c365ed7 \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "cd /root/E-shop",
              "git pull origin main",
              "npm install",
              "npm run build",
              "sudo rm -rf /usr/share/nginx/html/*",
              "sudo cp -r dist/* /usr/share/nginx/html/",
              "sudo systemctl restart nginx"
            ]'
